# Application log configuration file that defines how to build the Logger

[App]
LoggerName:AppLogger
GlobalLogLevel:INFO

[ColorConsoleSink]
LogLevel:INFO

[TextFileSink]
LogFileName:App
LogFileExtension:.log
LogLevel:INFO
