# Defines Core Configurable Objects

[App]
OutputDirectory=output

[App.Logger]
LoggerName=AppLogger
GlobalLogLevel=INFO

# This is just a Container for the Sinks, Makes it easier to grab them in the code
[App.Logger.Sinks]

[App.Logger.Sinks.ColorConsoleSink]
LogLevel=INFO

[App.Logger.Sinks.TextFileSink]
LogFileName=App
LogFileExtension=.log
LogLevel=INFO