# Defines Core Configurable Objects
# Meaning, Only Configurables that are instantiated once throughout the program

# BEGINNING APP ----------------------------------
[App]

[App.Logger]
LoggerName=AppLogger
GlobalLogLevel=NONE

[App.Logger.Sinks]

[App.Logger.Sinks.ColorConsoleSink]
LogLevel=INFO

[App.Logger.Sinks.TextFileSink]
LogFileName=App
LogFileExtension=.log
LogLevel=INFO

# END APP ----------------------------------------

# BEGINNING STATESTACK ---------------------------

[StateStack]

[StateStack.Logger]
LoggerName=StateStackLogger
GlobalLogLevel=NONE

[StateStack.Logger.Sinks]

[StateStack.Logger.Sinks.TextFileSink]
LogFileName=StateStack
LogFileExtension=.log
LogLevel=INFO

# END STATESTACK ---------------------------------

# BEGINNING MESSAGE NETWORK ----------------------

[MessageNetwork]

[MessageNetwork.Logger]
LoggerName=MessageNetworkLogger
GlobalLogLevel=NONE

[MessageNetwork.Logger.Sinks]

[MessageNetwork.Logger.Sinks.TextFileSink]
LogFileName=MessageNetwork
LogFileExtension=.log
LogLevel=INFO

# END MESSAGE NETWORK ----------------------------