# Defines Core Configurable Objects
# Meaning, Only Configurables that are instantiated once throughout the program

# List of All Core Configurables
# - App
# - StateStack
# - Message Network
# - Scene

# BEGINNING APP ----------------------------------

[App]
logging_enabled = true

[App.Logger]
logger_name = "AppLogger"
global_log_level = "NONE"
sinks = [ "ColorConsoleSink", "TextFileSink" ]

[App.Logger.ColorConsoleSink]
log_level = "INFO"

[App.Logger.TextFileSink]
log_file_name = "App"
log_file_extension = ".log"
log_level = "INFO"

# END APP ----------------------------------------

# BEGINNING STATESTACK ---------------------------

[StateStack]
logging_enabled = true

[StateStack.Logger]
logger_name = "StateStackLogger"
global_log_level = "NONE"
sinks = [ "TextFileSink" ]

[StateStack.Logger.TextFileSink]
log_file_name = "StateStack"
log_file_extension = ".log"
log_level = "INFO"

# END STATESTACK ---------------------------------

# BEGINNING MESSAGE NETWORK ----------------------

[MessageNetwork]
logging_enabled = true

[MessageNetwork.Logger]
logger_name = "MessageNetworkLogger"
global_log_level = "NONE"
sinks = [ "TextFileSink" ]

[MessageNetwork.Logger.TextFileSink]
log_file_name = "MessageNetwork"
log_file_extension = ".log"
log_level = "INFO"

# END MESSAGE NETWORK ----------------------------

# BEGINNING SCENE --------------------------------

[Scene]
logging_enabled = true

[Scene.Logger]
logger_name = "SceneLogger"
global_log_level = "NONE"
sinks = [ "TextFileSink" ]

[Scene.Logger.TextFileSink]
log_file_name = "Scene"
log_file_extension = ".log"
log_level = "INFO"

# END SCENE --------------------------------------