# Root file contains a list of other Configuration Files

[Configuration]
# out_directory = 'myOutput'

# # Path to where your asset files are
# asset_directory = 'assets'
# asset_font_directory = 'fonts'
# asset_texture_directory = 'textures'

[Configuration_Files]
files = ['core_configurables.toml', 'prefabs.toml']